### ISSUE TITLE
web ui 下载

### ISSUE THREAD

**Issue by jk9527** [helson-lin/douyin_no_watermark#2]
[ffandown-front](https://github.com/helson-lin/ffandown-front) 可以套这个UI在web下载吗？

**Comment by helson-lin** [comment]
套这个UI是啥意思 这个就是前端的包

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月23日 14:00 |
| 收件人 | helson-lin/douyin_no_watermark ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/douyin_no_watermark] web ui 下载 (Issue #2) |

ffandown-front 可以套这个UI在web下载吗？

**Comment by helson-lin** [comment]
默认的前端服务就是这个

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月23日 14:00 |
| 收件人 | helson-lin/douyin_no_watermark ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/douyin_no_watermark] web ui 下载 (Issue #2) |

ffandown-front 可以套这个UI在web下载吗？

**Comment by jk9527** [comment]
可能是我描述有误，没有苹果手机，试了不能像ffandown那样在web创建任务下载并保存到本地。只有api，post请求返回下载链接，需要再配合使用别的工具下载吗？

**Comment by helson-lin** [comment]
抱歉 我看错仓库了 这个我没有写web页面 需要自己调用API 安卓手机

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月23日 17:15 |
| 收件人 | helson-lin/douyin_no_watermark ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/douyin_no_watermark] web ui 下载 (Issue #2) |

可能是我描述有误，没有苹果手机，试了不能像ffandown那样在web创建任务下载并保存到本地。只有api，post请求返回下载链接，需要再配合使用别的工具下载吗？

**Comment by helson-lin** [comment]
看今晚有没有空随便写一个

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月23日 17:15 |
| 收件人 | helson-lin/douyin_no_watermark ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/douyin_no_watermark] web ui 下载 (Issue #2) |

可能是我描述有误，没有苹果手机，试了不能像ffandown那样在web创建任务下载并保存到本地。只有api，post请求返回下载链接，需要再配合使用别的工具下载吗？

**Comment by jk9527** [comment]
好的，麻烦了，不着急你得空随便写个能用就行，暂时使用postman工具请求，返回video不能直接使用迅雷下载，试了浏览器可以打开，再用猫抓插件可以下载下来。

**Comment by helson-lin** [comment]
我的项目 你直接在电报联系我就行 有空闲时间就写下


| |
helsonlin
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月23日 17:48 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [helson-lin/douyin_no_watermark] web ui 下载 (Issue #2) |

好的，麻烦了，不着急你得空随便写个能用就行，暂时使用postman工具请求，返回video不能直接使用迅雷下载，试了浏览器可以打开，再用猫抓插件可以下载下来。

**Comment by helson-lin** [comment]
UI在v0.0.8已添加
