### ISSUE TITLE
报错了,修修

### ISSUE THREAD

**Issue by a5582323** [helson-lin/douyin_no_watermark#3]
![image](https://github.com/helson-lin/douyin_no_watermark/assets/11252129/45d5a261-14b7-42d2-9f15-d9f6421fe200)

**Comment by helson-lin** [comment]
你复制的解析地址是啥，这个错误是没有找到视频id

**Comment by a5582323** [comment]
https://v.douyin.com/iLpeEARV/,这个链接会出现你说的没找到视频id的错误,但是现在又有个新的错误

**Comment by a5582323** [comment]
request
{
  "url": "https://v.douyin.com/iLDRPkcb/"
}
response
{"code":1,"msg":"FetchError: invalid json response body at https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7324705782094777641&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSLHivANnEftEkaqU9WcBrx reason: Unexpected end of JSON input","data":null}

**Comment by helson-lin** [comment]
0.0.9版本已经修复 请下载新版本使用

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月27日 16:36 |
| 收件人 | helson-lin/douyin_no_watermark ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/douyin_no_watermark] 报错了,修修 (Issue #3) |

request
{
"url": "https://v.douyin.com/iLDRPkcb/"
}
response
{"code":1,"msg":"FetchError: invalid json response body at https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7324705782094777641&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSLHivANnEftEkaqU9WcBrx reason: Unexpected end of JSON input","data":null}

**Comment by helson-lin** [comment]
正常了请反馈一下

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月27日 16:36 |
| 收件人 | helson-lin/douyin_no_watermark ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/douyin_no_watermark] 报错了,修修 (Issue #3) |

request
{
"url": "https://v.douyin.com/iLDRPkcb/"
}
response
{"code":1,"msg":"FetchError: invalid json response body at https://www.douyin.com/aweme/v1/web/aweme/detail/?device_platform=webapp&aid=6383&channel=channel_pc_web&aweme_id=7324705782094777641&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1344&screen_height=756&browser_language=zh-CN&browser_platform=Win32&browser_name=Firefox&browser_version=110.0&browser_online=true&engine_name=Gecko&engine_version=109.0&os_name=Windows&os_version=10&cpu_core_num=16&device_memory=&platform=PC&webid=7158288523463362079&msToken=abL8SeUTPa9-EToD8qfC7toScSADxpg6yLh2dbNcpWHzE0bT04txM_4UwquIcRvkRb9IU8sifwgM1Kwf1Lsld81o9Irt2_yNyUbbQPSUO8EfVlZJ_78FckDFnwVBVUVK&X-Bogus=DFSzswSLHivANnEftEkaqU9WcBrx reason: Unexpected end of JSON input","data":null}

**Comment by a5582323** [comment]
已解决,就很棒

**Comment by helson-lin** [comment]
好的 issue 我关闭了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年01月28日 13:11 |
| 收件人 | helson-lin/douyin_no_watermark ***@***.***> |
| 抄送人 | helson-lin ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [helson-lin/douyin_no_watermark] 报错了,修修 (Issue #3) |

已解决,就很棒
