### ISSUE TITLE
docker镜像拉取失败

### ISSUE THREAD

**Issue by lroronoazoro** [helson-lin/douyin_no_watermark#4]
请问一下, 镜像拉取失败是啥问题, 是不是我网络不行, 自己构建镜像可用, 我想问一下, docker run 之后, 会返回一个 server 3000,  这种情况是对的吗?

**Comment by helson-lin** [comment]
允许之后直接访问3000端口 服务启动在3000

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月15日 02:36 |
| 收件人 | helson-lin/douyin_no_watermark ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/douyin_no_watermark] docker镜像拉取失败 (Issue #4) |

请问一下, 镜像拉取失败是啥问题, 是不是我网络不行, 自己构建镜像可用, 我想问一下, docker run 之后, 会返回一个 server 3000, 这种情况是对的吗?
