### ISSUE TITLE
能在线播放，下载提示无法下载-没有权限

### ISSUE THREAD

**Issue by Sumzibuyu** [helson-lin/douyin_no_watermark#7]
如题    -这是什么操作，浏览器不让下载，手机浏览器下载成功，视频嵌入了版权保护？？

**Comment by Sumzibuyu** [comment]
edge浏览器

**Comment by helson-lin** [comment]
用的什么设备  什么浏览器 测试都是正常可以下载的  拿到的就是直链

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月08日 13:02 |
| 收件人 | helson-lin/douyin_no_watermark ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [helson-lin/douyin_no_watermark] 能在线播放，下载提示无法下载-没有权限 (Issue #7) |

如题 -这是什么操作，浏览器不让下载，手机浏览器下载成功，视频嵌入了版权保护？？

**Comment by helson-lin** [comment]
刚测试没有问题的 不清楚你是怎么下载的

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月08日 13:02 |
| 收件人 | helson-lin/douyin_no_watermark ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | Re: [helson-lin/douyin_no_watermark] 能在线播放，下载提示无法下载-没有权限 (Issue #7) |

edge浏览器
